routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('image/{type}/{filename}', 'ImageController@index')
    ->name('image')
;

Route::group([
    'prefix' => LaravelLocalization::setLocale(),
    'middleware' => [ 'localizationRedirect', 'localeViewPath' ],
], function() {
    Route::get('/', 'HomeController@index')->name('home');
    Route::get('company/{id}', 'CompaniesController@company')->name('company');
    Route::get('companies', 'CompaniesController@companies')->name('companies');
    Route::get('mosque/{id}', 'MosquesController@mosque')->name('mosque');
    Route::get('mosques', 'MosquesController@mosques')->name('mosques');
    Route::post('order/company/{id}', 'OrdersController@data')->name('order.data');
    Route::get('order/mosque/{id}', 'OrdersController@mosque')->name('order.mosque');
    Route::get('order/product/{id}', 'OrdersController@product')->name('order.product');
    Route::get('order/company/{id}', 'OrdersController@company')->name('order.company');
    Route::get('order', 'OrdersController@index')->name('order');
    Route::post('order', 'OrdersController@store')->name('order.submit');
});

# Admin Routes!
Route::group(['namespace' => 'Admin', 'prefix' => 'admin', 'as' => 'admin'], function () {

    Route::get('/', 'HomeController@index')->name('.main');

    Route::get('/login', 'Auth\LoginController@showLoginForm')->name('.login');
    Route::post('login', 'Auth\LoginController@login');
    Route::post('logout', 'Auth\LoginController@logout')->name('.logout');
    Route::get('logout', function () {
        Auth::logout();
        return redirect('/admin');
    })->name('.logout');

    Route::group(['middleware' => ['auth.admin']], function () {

        #if(function_exists('admin_resource')) {
            admin_resource('users', 'UsersController', 'users');
            admin_resource('translations', 'TranslationsController', 'translations');
            admin_resource('cities', 'CitiesController', 'cities');
            admin_resource('neighborhoods', 'NeighborhoodsController', 'neighborhoods');
            Route::get('neighborhoods/list/{city_id}', 'NeighborhoodsController@list')->name('.neighborhoods.list');
            admin_resource('mosques', 'MosquesController', 'mosques');
            admin_resource('companies', 'CompaniesController', 'companies');
            admin_resource('products', 'ProductsController', 'products');
            admin_resource('places', 'PlacesController', 'places');
            admin_resource('pages', 'PagesController', 'pages');
            admin_resource('orders', 'OrdersController', 'orders');
        #}

        Route::get('contacts/export', 'ContactsController@export')->name('.contacts.export');
        Route::post('contacts/data', 'ContactsController@data')->name('.contacts.data');
        Route::resource('contacts', 'ContactsController');

        Route::get('options', 'OptionsController@index')->name('.options.index');
        Route::post('options', 'OptionsController@update')->name('.options.update');

    });

});

app/Mosque.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Mosque extends Model
{
    function city() {
        return $this->belongsTo(City::class);
    }

    function neighborhood() {
        return $this->belongsTo(Neighborhood::class);
    }


    function getImageUrlAttribute() {
        return route('image', ['mosque', $this->image]);
    }

    function getUrlAttribute() {
        return route('mosque', $this->id);
    }

    function getOrderUrlAttribute() {
        return route('order.mosque', $this->id);
    }

}

resources/views/companies.blade.php
@extends('layouts.app')
@section('content')

    <section class="page-header text-left">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <ul class="breadcrumb text-left">
                        <li><a href="#">الرئيسية</a></li>
                        <li class="active">عرض شركات المياه</li>
                    </ul>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12 text-left">
                    <h1 class="text-left">عرض شركات المياه</h1>
                </div>
            </div>
        </div>
    </section>

    <div class="container">

        <div class="row">
            <div class="col-md-12">
                <hr class="tall">
            </div>
        </div>

        <div class="row">
            <div class="col-md-6">
                <h1 class="mb-none"><strong>شركات المياه</strong></h1>
            </div>
        </div>

        <div class="row">

            <div class="masonry-loader masonry-loader-showing">
                <ul class="products product-thumb-info-list" data-plugin-masonry>
                    @foreach($companies as $company)
                        <li class="col-md-3 col-sm-6 col-xs-12 product">
									<span class="product-thumb-info">
										<a href="{{ $company->url }}">
											<span class="">
                                            <img src="{{ $company->image_url }}" class="img-responsive img-main" alt="">
											</span>
										</a>
										<span class="product-thumb-info-content">
											<a href="{{ $company->url }}" class="text-left">
											<span class="thumb-info-caption-title text-uppercase text-color-dark font-weight-bold">{{ $company->name }}</span>
											{{--<p>معلومات عن شركة المياه</p>--}}
											</a>
										</span>
									</span>
                        </li>
                        @endforeach

                </ul>
            </div>

        </div>

        <div class="row">
            <div class="col-md-12">
                @if($companies)
                    {{ $companies->links() }}
                @endif
            </div>
        </div>

    </div>


@endsection

resources/views/company.blade.php
@extends('layouts.app')
@section('content')

	<section class="page-header text-left">
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<ul class="breadcrumb text-left">
						<li><a href="#">الرئيسية</a></li>
						<li class="active">عروض شركة المياه</li>
					</ul>
				</div>
			</div>
			<div class="row">
				<div class="col-md-12 text-left">
					<h1 class="text-left">عروض شركة المياه</h1>
				</div>
			</div>
		</div>
	</section>

	<div class="container">

		<div class="row">
			<div class="col-md-12">
				<hr class="tall">
			</div>
		</div>

		<div class="row">
			<div class="col-md-6">

				<div class="thumbnail">
					<img src="{{ $company->image_url }}" class="img-responsive img-rounded" alt="">
				</div>
			</div>

			<div class="col-md-6">

				<div class="summary entry-summary">

					<h1 class="mb-none"><strong>{{ $company->name }}</strong></h1>

					<hr class="tall">
					<p class="taller">{{ $company->description }}</p>
					<a href="{{ $company->order_url }}" class="btn btn-primary btn-icon">طلب شراء</a>



				</div>


			</div>
		</div>


		<div class="row">
			<div class="col-md-12">
				<hr class="tall">

				<h4 class="mb-md text-uppercase">عروض <strong>الأسعار</strong></h4>

				<div class="row">

					<ul class="products product-thumb-info-list">
						@foreach($company->products as $product)
							<li class="col-md-3 col-sm-6 col-xs-12 product">
								<span class="product-thumb-info">
									<a href="{{ $product->url }}">
										<span class=""><img src="{{ $product->image_url }}" class="img-responsive" alt=""></span>
									</a>
									<span class="product-thumb-info-content text-center">
										<a href="{{ $product->url }}" class="text-center">
										<span class="thumb-info-caption-title text-uppercase text-color-dark font-weight-bold">{{ $product->name }}</span>
										<p>{{ $product->description }}</p>
											<a class="btn btn-primary" href="{{ $product->order_url }}">{{ $product->price }} ريال</a>
										</a>
									</span>
								</span>
							</li>
						@endforeach
					</ul>

				</div>
			</div>
		</div>
	</div>


@endsection

resources/views/mosque.blade.php
@extends('layouts.app')
@section('content')

	<section class="page-header text-left">
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<ul class="breadcrumb text-left">
						<li><a href="{{ route('home') }}">الرئيسية</a></li>
						<li class="active">عروض شركة المياه</li>
					</ul>
				</div>
			</div>
			<div class="row">
				<div class="col-md-12 text-left">
					<h1 class="text-left">عروض شركة المياه</h1>
				</div>
			</div>
		</div>
	</section>

	<div class="container">

		<div class="row">
			<div class="col-md-12">
				<hr class="tall">
			</div>
		</div>

		<div class="row">
			<div class="col-md-6">

				<div class="thumbnail">
					<img src="{{ $mosque->image_url }}" class="img-responsive img-rounded" alt="">
				</div>
			</div>

			<div class="col-md-6">

				<div class="summary entry-summary">

					<h1 class="mb-none"><strong>{{ $mosque->name }}</strong></h1>

					<hr class="tall" />
					<p class="taller">{{ $mosque->description }}</p>
					<hr class="tall" />
					<p class="taller address">{{ $mosque->address }}</p>
					<a href="{{ $mosque->order_url }}" class="btn btn-primary btn-icon">طلب شراء</a>

				</div>


			</div>
		</div>

	</div>


@endsection

resources/views/mosques.blade.php
@extends('layouts.app')
@section('content')

    <section class="page-header text-left">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <ul class="breadcrumb text-left">
                        <li><a href="#">الرئيسية</a></li>
                        <li class="active">عرض المساجد</li>
                    </ul>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12 text-left">
                    <h1 class="text-left">عرض المساجد</h1>
                </div>
            </div>
        </div>
    </section>

    <div class="container">

        <div class="row">
            <div class="col-md-12">
                <hr class="tall">
            </div>
        </div>

        <div class="row">
            <div class="col-md-6">
                <h1 class="mb-none"><strong>المساجد</strong></h1>
            </div>
        </div>

        <div class="row">

            <div class="masonry-loader masonry-loader-showing">
                <ul class="products product-thumb-info-list" data-plugin-masonry>
                    @foreach($mosques as $mosque)
                    <li class="col-md-3 col-sm-6 col-xs-12 product">
									<span class="product-thumb-info">
										<a href="{{ $mosque->url }}">
											<span class="">
										<img src="{{ $mosque->image_url }}" class="img-responsive" alt="">
											</span>
										</a>
										<span class="product-thumb-info-content">
											<a href="{{ $mosque->url }}" class="text-left">
											<span class="thumb-info-caption-title text-uppercase text-color-dark font-weight-bold">{{ $mosque->name }}</span>
											<p>{{ $mosque->city->name }} - {{ $mosque->neighborhood->name }}</p>
											</a>
										</span>
									</span>
                    </li>
                    @endforeach
                </ul>
            </div>

        </div>

        <div class="row">
            <div class="col-md-12">

                @if($mosques)
                {{ $mosques->links() }}
                @endif
            </div>
        </div>

    </div>

@endsection